name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: src
      
    - name: Test
      run: dotnet test src/SubscriptionTracker.UnitTests/SubscriptionTracker.UnitTests.csproj --no-build --verbosity normal
